runtime: python27
api_version: 1
env: standard
threadsafe: false
instance_class: F1

handlers:

- url: /(.*\.(gif|png|jpg|ico|js|css|zip))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|zip))

- url: .*
  script: main.py
  
  
  
  
  
  
  

